//! Build script: generate an embedded manifest of every campaign/scenario/map JSON.
//!
//! Base-game content used to be pulled in with a single hardcoded JSON include
//! per loader (one campaign, one scenario), so adding a mission meant editing
//! Rust. Instead we scan `assets/campaigns/`, `assets/scenarios/`, and
//! `assets/maps/` here at build time and emit toolkit-backed JSON arrays. The
//! result:
//!   - WASM builds get every file embedded automatically (the "WASM embedded
//!     manifest") — add a file, rebuild, it ships.
//!   - Native builds additionally re-scan the directory at runtime (see
//!     `data::content_source`), so a dropped-in mission loads with no rebuild.
//!   - The loose `assets/campaigns`, `assets/scenarios`, and `assets/maps`
//!     source directories can be packed into a zip on publish (see
//!     `asset_packs.json`) without breaking anything at runtime, since nothing
//!     needs them to still exist on disk.
//!
//! Either way, authoring a mission is pure content work — no code changes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let mut generated = String::from("// @generated by build.rs — do not edit.\n\n");
    emit_dir(
        &mut generated,
        &manifest_dir,
        "assets/campaigns",
        "EMBEDDED_CAMPAIGNS",
    );
    emit_dir(
        &mut generated,
        &manifest_dir,
        "assets/scenarios",
        "EMBEDDED_SCENARIOS",
    );
    emit_dir_by_filename(
        &mut generated,
        &manifest_dir,
        "assets/maps",
        "EMBEDDED_MAPS",
    );

    let dest = Path::new(&out_dir).join("embedded_content.rs");
    fs::write(&dest, generated).expect("write embedded_content.rs");
}

/// Emit a static array of toolkit-embedded JSON strings for
/// every `*.json` in `<manifest_dir>/<rel>`, sorted for deterministic output.
fn emit_dir(out: &mut String, manifest_dir: &str, rel: &str, const_name: &str) {
    let dir = Path::new(manifest_dir).join(rel);
    // Re-run whenever the directory itself changes (files added/removed)...
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut json_files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.extension().and_then(|x| x.to_str()) == Some("json"))
        .collect();
    json_files.sort();

    out.push_str(&format!("pub static {const_name}: &[&str] = &[\n"));
    for path in &json_files {
        // ...and whenever any embedded file's contents change.
        println!("cargo:rerun-if-changed={}", path.display());
        // The toolkit JSON include accepts forward slashes on every platform.
        let literal = path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    macroquad_toolkit::include_json_str!(\"{literal}\"),\n"
        ));
    }
    out.push_str("];\n\n");
}

/// Same as `emit_dir`, but pairs each file with its filename so callers can
/// look a specific map up by the path they were asked to load (e.g.
/// `"assets/maps/level_1.json"` -> embedded entry `"level_1.json"`), rather
/// than merging everything into one id-keyed set.
fn emit_dir_by_filename(out: &mut String, manifest_dir: &str, rel: &str, const_name: &str) {
    let dir = Path::new(manifest_dir).join(rel);
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut json_files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.extension().and_then(|x| x.to_str()) == Some("json"))
        .collect();
    json_files.sort();

    out.push_str(&format!("pub static {const_name}: &[(&str, &str)] = &[\n"));
    for path in &json_files {
        println!("cargo:rerun-if-changed={}", path.display());
        let filename = path
            .file_name()
            .and_then(|f| f.to_str())
            .expect("map file name");
        let literal = path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    (\"{filename}\", macroquad_toolkit::include_json_str!(\"{literal}\")),\n"
        ));
    }
    out.push_str("];\n\n");
}
